openapi: 3.0.0
info:
  title: API de Produtos
  version: 1.0.0
paths:
  /health:
    get:
      summary: Verificar status da aplicação
      responses:
        '200':
          description: Status da aplicação
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
  /products:
    get:
      summary: Listar todos os produtos
      responses:
        '200':
          description: Lista de produtos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
    post:
      summary: Criar produto
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '201':
          description: Produto criado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
  /products/{id}:
    get:
      summary: Buscar produto específico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Informações do produto
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    put:
      summary: Atualizar produto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProductInput'
      responses:
        '200':
          description: Produto atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Product'
    delete:
      summary: Deletar produto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: Produto deletado
components:
  schemas:
    Product:
      type: object
      properties:
        id:
          type: string
        nome:
          type: string
        preço:
          type: number
        descrição:
          type: string
    ProductInput:
      type: object
      properties:
        nome:
          type: string
        preço:
          type: number
        descrição:
          type: string
